### ISSUE TITLE
instructions on README may not always work

### ISSUE THREAD

**Issue by abrin** [qa/arquillian-phantom-driver#16]
I spent quite a while debugging an issue when trying to pass parameters into phantomJS.   The root of the issue is that this didn't work:
````
WebDriver driver = new PhantomJSDriver(
        ResolvingPhantomJSDriverService.createDefaultService(),
        capabilities);
````

The following was the issue, the ResolvingPhantomJSDriverService needed to be configured with the capabilities. (see line 173). This is specifically the case when you need to configure the driver with CommandLineArguments.  The following works:

````
WebDriver driver = new PhantomJSDriver(
        ResolvingPhantomJSDriverService.createDefaultService(capabilities),
        capabilities);
````

**Comment by smiklosovic** [comment]
@abrin could you please send a PR with your findings for README file so other people could benefit from your effort?

Thanks!
