### ISSUE TITLE
phantomjs lookup mechanism does not work always

### ISSUE THREAD

**Issue by flexguse** [qa/arquillian-phantom-driver#2]
I use the arquillian-phantom-binary in a servlet container and had lots of trouble with resolving the included phantomjs binary - it didn't work.

A working solution was to put the binaries as resources into the JAR and using something like "getClass().getResource(...)" to access the binary. Additionally the current implementation can't cope with blanks in the binary URL because the URL.file is not URLDecoded.

Please see https://bitbucket.org/empulse/selenium-phantomjs-driver-clone/overview for a possible solution.

**Comment by MatousJobanek** [comment]
Closing this issue because of long inactivity. Feel free to reopen it if you don't agree with this action.
