### ISSUE TITLE
PhantomJS configuration is not customizable via Capabilities/arquillian.xml

### ISSUE THREAD

**Issue by s7orm** [qa/arquillian-phantom-driver#23]
In theory the MavenPhantomJSBinaryResolver supports configuring the PhantomJS version via "phantomjs.binary.version", but this only works if the version has been set as a system property, but not via a Capabilities object (which is also created from the arquillian.xml descriptor).
It can be fixed by passing the Capabilities object to the ResolverConfiguration.get() invokation (line 68 on current master).

**Comment by MatousJobanek** [comment]
Hi,
thanks for pointing this out.
see the PR: https://github.com/qa/arquillian-phantom-driver/pull/24

**Comment by MatousJobanek** [comment]
PR merged. Closing this issue as resolved. Feel free to reopen it if you still have the problem
